baseURL = 'https://example.org/'
languageCode = 'pl-pl'
title = 'Matura Matematyka'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
   BookSection = "*"
   math = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'

